server:
  port: 10012
spring:
  application:
    name: school-oauth
  datasource:
    username: root
    password: 897229594op
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schooltao_platform?useSSL=true&useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 86400
      #最大连接等待时间 6s
      max-wait: 6000
      #最小连接池数量
      min-idle: 1
      validation-query: SELECT 1
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      #缓存statements，这样执行效率更高
      pool-prepared-statements: true
      filter:
        stat:
          merge-sql: true
      stat-view-servlet:
        login-username: root
        login-password: 897229594op
  #redis
  redis:
    host: 127.0.0.1
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  safe-delete: true
  safe-update: true
  not-empty: true

#客户端密钥明文
school:
  oauth2:
    client:
      secret: admin
