server:
  port: 10013
spring:
  application:
    name: school-good
  datasource:
    username: root
    password: 897229594op
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/schooltao_platform?useSSL=true&useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
    druid:
      initial-size: 1
      max-active: 86400
      max-wait: 6000
      min-idle: 1
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filter:
        stat:
          merge-sql: true
      stat-view-servlet:
        login-username: root
        login-password: 897229594op
  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          endpoints: http://localhost:9200
  elasticsearch:
    rest:
      uris: http://localhost:9200
      connection-timeout: 2
  redis:
    host: localhost
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 4
    timeout: 6000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 1000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml

mapper:
  not-empty: true
  safe-update: true
  safe-delete: true

#客户端密钥明文
school:
  oauth2:
    client:
      secret: admin